safchain/ethtool

- ethtool.go
Was working with solarflare cards and they returned a lot more stats than the
old value could handle.
> raised the limit for MAX_GSTRINGS size by 100 percent

- README.md
- ethtool.go
- ethtool_cmd.go
- ethtool_msglvl.go
In every method, a socket is created. When using ethtool
inside a namespace, it requires switching to the namespace
for every call - as staying inside the namespace is risky
in Go. This commit introduces a Ethtool that creates the
socket once and reuses it for all the following calls
> Add Ethtool type

- ethtool.go
When using network namespaces, using syscalls triggers the
Go runtime that can create a new thread in the same namespace
than the one doing the syscall, which can cause hard to debug
problems.
> Use syscall.RawSyscall to open netlink socket

- ethtool.go
Bumping the value to 1000 to resolve this error with some room.
"map[] ethtool currently doesn't support more than 200 entries, received 729"
> Increase max_gstrings value

- ethtool.go
This PR adds support to request changes in the device feature configuration.
Example:
```go
t, _ := ethtool.NewEthtool()
_ := t.Configure("enp5s0", map[string]bool{
"tx-checksum-ipv4": true,
})
```
> Support requesting feature changes

- ethtool.go
Stats are null terminated strings, but output may contain garbage between them. Current code
that converts C strings to Go strings doesn't handle these cases, as it only trims zeros at the
end of the string.
Fix based on: https://stackoverflow.com/a/12377539
Fixes: #4
Signed-off-by: Haggai Eran <haggai.eran@gmail.com>
> Fix garbled statistics names

- ethtool.go
Bumping value to 4096 to resolve with some room.
`ethtool currently doesn't support more than 1000 entries, received 2484`
> Increase max_gstrings value to 4096

- .travis.yml
- ethtool.go
- ethtool_cmd.go
- ethtool_msglvl.go
Added methods to retrieve channels count, coalesce config params.
Changed DriverInfo method to return an exported struct.
Switched to golang.org/x/sys/unix from syscall. https://groups.google.com/forum/#!topic/golang-dev/cEASnHIXmLI
package syscall is locked down and should only be called by internal packages, external packages should use golang.org/x/sys
@safchain - Can this be merged?
> New methods (GetCoalesce, GetChannels). Switched to golang.org/x/sys from syscall

- ethtool.go
Bumping value to 8192. 4096 was still not enough, this is to continue #29 and #28
> Increase max_gstrings value to 8192

- ethtool.go
For example mlxsw_spectrum has 'a_mac_control_frames_transmitted' key, which triggers panic because there is no \x00 padding.
> fix panic if key without padding

- .travis.yml
Adding Power Support.
Adding power support ppc64le
This is part of the Ubuntu distribution for ppc64le. This helps us simplify testing later when distributions are re-building and re-releasing. For more info tag @gerrith3.
The build is successful on both arch: amd64/ppc64le, Please find the Travis Link: https://travis-ci.com/github/santosh653/ethtool
Please Let me know if you need any other details or If I am missing any..
Thank You !!
> AddingPowerSupportFor_golang-github-safchain-ethtool

- ethtool.go
When attempting to use the ethtool stats collector in prometheus node exporter which leverages this lib, I'm hitting the 8k limit set in MAX_GSTRINGS due to NICs with a large number of channels and rx/tx queues due to overall system core counts (i.e. 128 cpu cores). This increases the overall number of stats exported:
```
Aug 03 00:02:08 node_exporter[1728339]: level=error ts=2021-08-03T00:02:08.271Z caller=ethtool_linux.go:154 collector=ethtool msg="ethtool stats error" err="ethtool currently doesn't support more than 8192 entries, received 8979">
```
This PR raises the MAX_GSTRINGS limit to 16k.
> Update MAX_GSTRINGS to 16384

- ethtool.go
As stated in Issue #45, the number of entries from ethtool stats can go beyond the current `MAX_GSTRINGS` limit with some firmware versions from certain NIC vendors. One example is Mellanox MT27800 ConnectX-5 with the following firmware.
```
$ ethtool -i enp1s0f0
driver: mlx5_core
version: 5.1-2.3.7
firmware-version: 16.28.4512 (DEL0000000016)
expansion-rom-version:
bus-info: 0000:01:00.0
supports-statistics: yes
supports-test: yes
supports-eeprom-access: no
supports-register-dump: no
supports-priv-flags: yes
``` 
Before the change (with added logs to show the error and # of entries):
```
[stephen@ld1 ethtool]$ go test -run TestStats -v
=== RUN   TestStats
Interface lo, err: operation not supported
Interface em1, len(stats) 72
Interface enp1s0f0, err: ethtool currently doesn't support …
```
> Update MAX_GSTRINGS to 32768

- ethtool.go
- ethtool_test.go
- example/main.go
Currently, one can acquire a bitmask of supported modes of operation by using the `GetCmdMapped` function:
```go
e, err := ethtool.NewEthtool()
if err != nil {
panic(err.Error())
}
defer e.Close()
cmdGet, err := e.CmdGetMapped(*name)
if err != nil {
panic(err.Error())
}
fmt.Printf("cmd get: %+d\n", cmdGet["Supported"])
```
Unfortunately, there is no information on what the individual bits mean. 
In this PR, I added the names of some supported capabilities (which I got from here: https://github.com/lyonel/lshw/blob/fdab06ac0b190ea0aa02cd468f904ed69ce0d9f1/src/core/network.cc#L113). This enables users of this library to seamlessly check, which capacities the interface in question supports.
closes #46
> Add Names for supported capabilities of interfaces

- Makefile
- ethtool.go
- ethtool_darwin.go
- ethtool_linux.go
When using this library in multi-os builds, the `sys/unix` flags for `ETHTOOL_LINK_MODE_*` fail to compile on darwin. This PR moves them into a `ethtool_linux.go` specific source file, and a stub in `ethtool_darwin.go` to not have any `supportedCapabilities`.
> Conditionally inject supportedCapabilities

- ethtool.go
Go runtime automatically adds this flag, but when using raw syscalls, it should be added manually.
Without this flag, the process leaks a file descriptor on fork/exec.
> fix: add SOCK_CLOEXEC to socket creation

- ethtool.go
- ethtool_test.go
The following changes introduce support for Indirection Table editing similar to the functionality provided by the following `ethtool` CLI commands:
```sudo ethtool --set-rxfh-indir $ETH equal 10``` or ```sudo ethtool --set-rxfh-indir $ETH weight 1 1```
- New functions:  ```GetIndir```, ```SetIndir```, ```fillIndirTable``` 
- New structs: ```Indir``` and ```SetIndir```
The ```GetIndir(intf string)``` function retrieves the current Indirection Table for the specified network interface, and returns an ```Indir```struct.
The ```SetIndir(intf string, setIndir SetIndir)``` function sets a new Indirection Table for the specified interface. The function accepts a ```SetIndir``` struct, which should have either: ```SetIndir.Equal``` value set or ```SetIndir.Weight``` slice set.
The function then …
> Added support for Indirection Table editing

- ethtool.go
- ethtool_link_settings.go
- ethtool_link_settings_test.go
- ethtool_linux.go
- example/main.go
fix #82 #33
This change introduces support for the `ETHTOOL_GLINKSETTINGS` and `ETHTOOL_SLINKSETTINGS` ioctls, providing a more modern and comprehensive way to configure network interface Link Settings compared to the older `ETHTOOL_GSET`/`SSET`.
*   **`GetLinkSettings(intfName string) (*LinkSettings, error)`**:
*   Retrieves the Link Settings for the specified network interface (`intfName`).
*   **Attempts first** to use the `ETHTOOL_GLINKSETTINGS` ioctl to get extended Link Settings.
*   If the kernel or driver does not support `GLINKSETTINGS` (returns an `EOPNOTSUPP` error), it **automatically falls back** to calling the older `CmdGet()` (using `ETHTOOL_GSET`) and converts the result to the new `LinkSettings` struct before returning.
*   Returns a pointer to a `LinkSettings` struct …
> Added Link Settings (GLINKSETTINGS/SLINKSETTINGS) Support

- ethtool.go
- ethtool_test.go
fix #104
Introduce sync pool to optimize large object allocation
```
$ benchstat bench.out.master bench.out.perf
goos: linux
goarch: amd64
pkg: github.com/safchain/ethtool
cpu: Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz
│ bench.out.master │            bench.out.perf            │
│      sec/op      │    sec/op     vs base                │
Stats/enp0s3-4       789.0µ ± 11%   398.5µ ± 14%  -49.49% (p=0.002 n=10)
Stats/enp0s8-4       777.9µ ±  8%   373.7µ ±  7%  -51.96% (p=0.000 n=10)
geomean              783.4µ         385.9µ        -50.74%
│ bench.out.master │            bench.out.perf             │
│       B/op       │     B/op       vs base                │
Stats/enp0s3-4    1300.243Ki ± 0%   3.576Ki ± 30%  -99.72% (p=0.000 n=10)
Stats/enp0s8-4    1300.238Ki ± 0%   3.896Ki ± 11%  -99.70% …
```
> optimize large slice alloc in Stats

- .github/dependabot.yml
- .github/workflows/golangci-lint.yml
- .github/workflows/unittests.yml
- .yamllint
- go.mod
- go.sum
The upstream Go support policy is to support the latest two major versions of Go. Update the `go` directive that specifies the minimum Go version required to support Go 1.23.x.
* Pin GitHub actions for supply chain security.
* Add matrix test for current Go versions.
* Bump golangci-lint version.
> Improve Go compatibility
